import type { Metadata, Viewport } from 'next';
import '@/styles/globals.css';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import { CookieProvider } from 'use-next-cookie';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1.0,
  maximumScale: 5.0,
  userScalable: true,
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CookieProvider>
      <html lang="ru">
        <body className={inter.className}>
          <Sidebar />
          <main className="appMain">{children}</main>
        </body>
      </html>
    </CookieProvider>
  );
}
